# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_pricing"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    marts:
        +materialized: table

    staging:
        +materialized: view

# Define variables here
vars:

  pricing_helloprint_models: [helloprint, helloprint_connect]

  pricing_products: [Flyers3, Postersv2, Businesscardsv2, Letterheads, Rollupbannersbudget, Envelopes, Postcards, Placemats, Stickersv2, Bookmarks, Roll-up banners (promo), Vouchers, Invitations, Foldedleafletshalffoldv2, Foldedleafletstrifoldv2, Labelsonrollpvcwhite, Beachflags, Folders, Notepads, Bookletsa4landscape, Bookletsa6, Bookletsa5landscape, Bookletsmediumsquare, Bookletslargesquare, Bookletsa5, Bookletsa4, Bookletsus]

  pricing_competitors_raw: {
      'Belgium' : [reclameland, drukwerkdeal, flyeralarm, flyeralarm_new, Print.com-TA-BE, Print.com-BE],
      'France' : [flyeralarm, flyeralarm_new, printoclock, realisaprint, Onlineprinters-feed, pixartprinting, pixart_puppeteer, Print24-FR, Onlineprinters-FR, Flyeralarm-FR, Saxoprint-FR, Exaprint-FR, Pixartprinting-FR, Realisaprint-FR, Printoclock-FR, Imprimerie-FR],
      'Netherlands' : [flyeralarm, flyeralarm_new, reclameland, drukwerkdeal, Print.com-TA-NL, Print.com-NL],
      'Spain' : [flyeralarm, flyeralarm_new, Onlineprinters-feed, pixart_puppeteer, Onlineprinters-ES, pixartprinting, Print24-ES, Flyeralarm-ES, Pixartprinting-ES, 360Imprimir-ES],
      'United_Kingdom' : [flyeralarm, solopress, routeoneprint, tradeprint, instantprint],
      'Germany' : [flyeralarm_new, Wirmachendruck-DE, Saxoprint-DE, Print24-DE, Onlineprinters-feed, Onlineprinters-DE, Flyeralarm-DE],
      'Italy' : [pixart_puppeteer, flyeralarm_new, flyeralarm, Saxoprint-IT, Printered-IT, Pressup-IT, Pixartprinting-IT, Onlineprinters-feed, Onlineprinters-IT, FlyerAlarm-IT, Fasterprint-IT, ADIVIN-IT, 4graph-IT]
  }

  pricing_competitors: {
      'Belgium' : [drukwerkdeal, flyeralarm, reclameland, Print_com_TA_BE, Print_com_BE],
      'France' : [flyeralarm, printoclock, realisaprint, Onlineprinters_feed, pixartprinting, pixart_puppeteer, Print24_FR, Onlineprinters_FR, Flyeralarm_FR, Saxoprint_FR, Exaprint_FR, Pixartprinting_FR, Realisaprint_FR, Printoclock_FR, Imprimerie_FR],
      'Netherlands' : [drukwerkdeal, flyeralarm, reclameland, Print_com_TA_NL, Print_com_NL],
      'Spain' : [flyeralarm, Onlineprinters_feed, pixart_puppeteer, Onlineprinters_ES, pixartprinting, Print24_ES, Flyeralarm_ES, Pixartprinting_ES, _360Imprimir_ES],
      'United_Kingdom' : [flyeralarm, solopress, routeoneprint, tradeprint, instantprint],
      'Germany' : [flyeralarm, Wirmachendruck_DE, Saxoprint_DE, Print24_DE, Onlineprinters_feed, Onlineprinters_DE],
      'Italy' : [pixart_puppeteer, flyeralarm, Saxoprint_IT, Printered_IT, Pressup_IT, Pixartprinting_IT, Onlineprinters_feed, Onlineprinters_IT, Fasterprint_IT, ADIVIN_IT, _4graph_IT]
  }

  pricing_competitor_mapping: {
      'flyeralarm' : ['flyeralarm_new', 'Flyeralarm-DE', 'FlyerAlarm-IT'],
      'Onlineprinters' : ['Onlineprinters-feed'],
      'Print24_ES' : ['Print24-ES'],
      'Onlineprinters_ES' : ['Onlineprinters-ES'],
      'Onlineprinters_feed' : ['Onlineprinters-feed'],
      'Print_com_TA_BE' : ['Print.com-TA-BE'],
      'Print_com_BE' : ['Print.com-BE'],
      'Print24_FR' : ['Print24-FR'],
      'Onlineprinters_FR' : ['Onlineprinters-FR'],
      'Flyeralarm_FR' : ['Flyeralarm-FR'],
      'Saxoprint_FR' : ['Saxoprint-FR'],
      'Exaprint_FR' : ['Exaprint-FR'],
      'Pixartprinting_FR' : ['Pixartprinting-FR'],
      'Realisaprint_FR' : ['Realisaprint-FR'],
      'Printoclock_FR' : ['Printoclock-FR'],
      'Imprimerie_FR' : ['Imprimerie-FR'],
      'Print_com_TA_NL' : ['Print.com-TA-NL'],
      'Print_com_NL' : ['Print.com-NL'],
      'Flyeralarm_ES' : ['Flyeralarm-ES'],
      'Pixartprinting_ES' : ['Pixartprinting-ES'],
      '360Imprimir_ES' : ['_360Imprimir-ES'],
      'Wirmachendruck_DE' : ['Wirmachendruck-DE'],
      'Saxoprint_DE' : ['Saxoprint-DE'],
      'Print24_DE' : ['Print24-DE'],
      'Onlineprinters_DE' : ['Onlineprinters-DE'],
      'Saxoprint_IT' : ['Saxoprint-IT'],
      'Pixartprinting_IT' : ['Pixartprinting-IT'],
      'Printered_IT' : ['Printered-IT'],
      'Pressup_IT' : ['Pressup-IT'],
      'Onlineprinters_IT' : ['Onlineprinters-IT'],
      'Fasterprint_IT' : ['Fasterprint-IT'],
      'ADIVIN_IT' : ['ADIVIN-IT'],
      '_4graph_IT' : ['4graph-IT']
      }

  pricing_country_mapping: {
      'United_Kingdom' : ['United Kingdom']
      }
