# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_pricing"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    marts:
        +materialized: table

    staging:
        +materialized: view

# Define variables here
vars:

  pricing_helloprint_models: [helloprint, helloprint_connect]

  pricing_products: [Flyers3, Postersv2, Businesscardsv2, Letterheads, Rollupbannersbudget, Envelopes, Postcards, Placemats, Stickersv2, Bookmarks, Roll-up banners (promo), Vouchers, Invitations]

  pricing_competitors_raw: {
      'Belgium' : [reclameland, drukwerkdeal, flyeralarm, flyeralarm_new],
      'France' : [flyeralarm, flyeralarm_new, printoclock, realisaprint, Onlineprinters-feed, pixartprinting, pixart_puppeteer],
      'Netherlands' : [flyeralarm, flyeralarm_new, reclameland, drukwerkdeal],
      'Spain' : [flyeralarm, flyeralarm_new, Onlineprinters-feed, pixart_puppeteer, Onlineprinters-ES, pixartprinting, Print24-ES],
      'United_Kingdom' : [flyeralarm, solopress, routeoneprint, tradeprint, instantprint]
  }

  pricing_competitors: {
      'Belgium' : [drukwerkdeal, flyeralarm, reclameland, Print.com-TA-BE, Print.com-BE],
      'France' : [flyeralarm, printoclock, realisaprint, Onlineprinters_feed, pixartprinting, pixart_puppeteer, Print24-FR, Onlineprinters-FR, Flyeralarm-FR, Saxoprint-FR, Exaprint-FR, Pixartprinting-FR, Realisaprint-FR, Printoclock-FR, Imprimerie-FR],
      'Netherlands' : [drukwerkdeal, flyeralarm, reclameland, Print.com-TA-NL, Print.com-NL],
      'Spain' : [flyeralarm, Onlineprinters_feed, pixart_puppeteer, Onlineprinters_ES, pixartprinting, Print24_ES, Flyeralarm-ES, Pixartprinting-ES, 360Imprimir-ES],
      'United_Kingdom' : [flyeralarm, solopress, routeoneprint, tradeprint, instantprint]
  }

  pricing_competitor_mapping: {
      'flyeralarm' : ['flyeralarm_new', 'flyeralarm_alpha', 'flyeralarm_beta'],
      'Onlineprinters' : ['Onlineprinters-feed'],
      'Print24_ES' : ['Print24-ES'],
      'Onlineprinters_ES' : ['Onlineprinters-ES'],
      'Onlineprinters_feed' : ['Onlineprinters-feed']
      }

  pricing_country_mapping: {
      'United_Kingdom' : ['United Kingdom']
      }
